<?php
//enable this when finished
//error_reporting(0);
if (file_exists('config.php')) {
    include('config.php');
}
else {
    include('../../config.php');
}

$conn = mysql_connect($sqlHost, $sqlUser, $sqlPass) or die("Can't connect to host : " . mysql_error());

$db = mysql_select_db($sqlDatabase, $conn) or die("Can't database to database: " . mysql_error());

$error = "";

if(empty($_POST['username']) || empty($_POST['password']) || empty($_POST['email'])) {
	$error = "Required Field is empty";
}
else {
	$username = $_POST['username'];
	$firstname = $_POST['firstname'];
	$lastname = $_POST['lastname'];
	$password = $_POST['password'];
	$email = $_POST['email'];
		
	// Used to prevent mysql injection
	$username = stripslashes($username);
	$username = mysql_real_escape_string($username);
	
	$password = stripslashes($password);	
	$password = mysql_real_escape_string($password);
	
	$email = stripslashes($email);
	$email= mysql_real_escape_string($email);
	
	$firstname = stripslashes($firstname);	
	$firstname = mysql_real_escape_string($firstname);
	
	$lastname = stripslashes($lastname);	
	$lastname= mysql_real_escape_string($lastname);
	
	$password = sha1($_POST['password']);
	
	$sql="SELECT * FROM Account WHERE Username= '$username'";
	$execute = mysql_query($sql, $conn) or die($sql . " : " . mysql_error());
	$rows = mysql_num_rows($execute);
		
	if ($rows == 1) {
		$error = "Username is already taken";
	}
	else {
		$sql="SELECT * FROM Account WHERE email = '$email'";
		$execute = mysql_query($sql, $conn) or die($sql . " : " . mysql_error());
		$rows = mysql_num_rows($execute);
		if ($rows == 1) {
			$error = "User with this email is already registered";
		}
		else {
            $firstname = ucfirst($firstname);
            $lastname = ucfirst($lastname);
			// parameters are (NULL *for autogenerated ID, username, password, email)
			$sql = "INSERT INTO Account (User_ID, Username, Firstname, Lastname, Password, Email) Values (NULL, '$username','$firstname', '$lastname', '$password', '$email')";
			$execute = mysql_query($sql, $conn) or die($sql . " : " . mysql_error());
			echo "You are now registered";
		}
	}
}
mysql_close($conn);
echo $error;
?>